#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

typedef enum { STATE_MAIN_MENU, STATE_WORLD, STATE_COMBAT, STATE_INVENTORY, STATE_SKILLS, STATE_DIALOG, STATE_DUNGEON, STATE_TOWN, STATE_QUEST_LOG, STATE_DEATH, STATE_PAUSE_MENU, STATE_LOADING, STATE_CHAR_SHEET, STATE_OPTIONS, STATE_SHOP } GameState;
extern GameState state;
extern HWND      g_hwnd;
