#pragma once

typedef enum { STATE_MAIN_MENU, STATE_WORLD, STATE_COMBAT, STATE_INVENTORY, STATE_SKILLS, STATE_DIALOG, STATE_DUNGEON, STATE_TOWN, STATE_QUEST_LOG, STATE_DEATH, STATE_PAUSE_MENU } GameState;
extern GameState state;
